// Auto-generated by scripts/list-cloudinary.mjs — do not edit.
// 20 clips from Cloudinary folder "BaywoodsVid",
// featured in the home video strip (next-cloudinary getCldVideoUrl + poster).

export interface FeaturedVideo {
  publicId: string;
  width: number;
  height: number;
  label: string;
}

export const featuredVideos: FeaturedVideo[] = [
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.43_wlm9cw", width: 478, height: 850, label: "Baywoods reel 1" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.42_nbcdh7", width: 478, height: 850, label: "Baywoods reel 2" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.42_1_rzazmq", width: 478, height: 850, label: "Baywoods reel 3" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.40_bgivmc", width: 478, height: 850, label: "Baywoods reel 4" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.39_xl305q", width: 576, height: 1024, label: "Baywoods reel 5" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.38_xk3cow", width: 478, height: 850, label: "Baywoods reel 6" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.38_1_gyzjem", width: 478, height: 850, label: "Baywoods reel 7" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.37_sfeqjl", width: 478, height: 850, label: "Baywoods reel 8" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.36_hapiff", width: 478, height: 850, label: "Baywoods reel 9" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.36_1_xk3zlt", width: 720, height: 1280, label: "Baywoods reel 10" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.35_nloyo8", width: 720, height: 1280, label: "Baywoods reel 11" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.35_1_edf1vf", width: 478, height: 850, label: "Baywoods reel 12" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.34_laqnem", width: 720, height: 1278, label: "Baywoods reel 13" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.33_qwzuym", width: 720, height: 1280, label: "Baywoods reel 14" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.33_1_ys5bjj", width: 478, height: 850, label: "Baywoods reel 15" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.31_tqjp13", width: 720, height: 1280, label: "Baywoods reel 16" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.31_2_b8ofac", width: 648, height: 1152, label: "Baywoods reel 17" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.45.31_1_lh8mqg", width: 478, height: 850, label: "Baywoods reel 18" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.44.04_uxap1k", width: 720, height: 1278, label: "Baywoods reel 19" },
  { publicId: "WhatsApp_Video_2026-06-29_at_11.44.02_s0i9ko", width: 478, height: 850, label: "Baywoods reel 20" },
];
