DO $$
BEGIN
  ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PENDING_PAYMENT';
  ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PAID';
  ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'VERIFICATION_PENDING';
  ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'VERIFIED';
  ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PACKED';
  ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'OUT_FOR_DELIVERY';
  ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'DELIVERED';
  ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'CANCELLED';
  ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'REFUNDED';
  ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'FAILED';
END $$;
